layout_spectrum: 0.7518797
name: fencingminds.com
typography_spectrum: 0.4793831
color:
  brandStrength: 0.3706844
  saturation: 0.2683586
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  lightness: 0.5443565
  rhythmicContrast: 0.2272682
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
