layout_spectrum: 0.7518797
typography_spectrum: 0.4793831
color:
  lightness: 0.5443565
  brandStrength: 0.3706844
  saturation: 0.2683586
  rhythmicContrast: 0.2272682
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
name: fencingminds.com
